FROM node:18-alpine3.15 AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install
COPY . .

ARG REACT_APP_ISPO_CONTRACT_ETH
ARG REACT_APP_STETH_CONTRACT
ARG REACT_APP_ISPO_CONTRACT_POLYGON
ARG REACT_APP_STMATIC_CONTRACT
ARG REACT_APP_ALCHEMY_API_KEY
ARG REACT_APP_PROJECTID_WALLET_CONNECT

ENV REACT_APP_ISPO_CONTRACT_ETH=$REACT_APP_ISPO_CONTRACT_ETH
ENV REACT_APP_STETH_CONTRACT=$REACT_APP_STETH_CONTRACT
ENV REACT_APP_ISPO_CONTRACT_POLYGON=$REACT_APP_ISPO_CONTRACT_POLYGON
ENV REACT_APP_STMATIC_CONTRACT=$REACT_APP_STMATIC_CONTRACT
ENV REACT_APP_ALCHEMY_API_KEY=$REACT_APP_ALCHEMY_API_KEY
ENV REACT_APP_PROJECTID_WALLET_CONNECT=$REACT_APP_PROJECTID_WALLET_CONNECT

RUN npm run build

FROM nginx:alpine
COPY ./nginx.conf /etc/nginx/conf.d/configfile.template

RUN rm -rf /usr/share/nginx/html/*

COPY --from=builder /app/build /usr/share/nginx/html
ENV PORT 8080
ENV HOST 0.0.0.0
EXPOSE 80
CMD sh -c "envsubst '\$PORT' < /etc/nginx/conf.d/configfile.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
