env:
  - key: REACT_APP_ISPO_CONTRACT_ETH
  - key: REACT_APP_STETH_CONTRACT
  - key: REACT_APP_ISPO_CONTRACT_POLYGON
  - key: REACT_APP_STMATIC_CONTRACT
  - key: REACT_APP_ALCHEMY_API_KEY
  - key: REACT_APP_PROJECTID_WALLET_CONNECT
